# see /usr/include/linux/input-event-codes.h for key codes

swipe:
  3:
    left:
      command: 'systemctl --user is-active lock.target -q || hyprctl --quiet dispatch workspace +1' # Alt + Right
    right:
      command: 'systemctl --user is-active lock.target -q || hyprctl --quiet dispatch workspace -1' # Alt + Left
    up:
      begin:
        command: 'systemctl --user is-active lock.target -q || amixer -q sset Master unmute'
      update:
        command: 'systemctl --user is-active lock.target -q || ~/.local/bin/volume-up 1' # KEY_VOLUMEUP
        threshold: 0.05
    down:
      begin:
        command: 'systemctl --user is-active lock.target -q || amixer -q sset Master unmute'
      update:
        command: 'systemctl --user is-active lock.target -q || ~/.local/bin/volume-down 1' # KEY_VOLUMEDOWN
        threshold: 0.05
  4:
    left:
      update:
        command: 'ydotool key 224:1 224:0' # KEY_BRIGHTNESSDOWN
    right:
      update:
        command: 'ydotool key 225:1 225:0' # KEY_BRIGHTNESSUP

hold:
  3:
    begin:
      command: 'systemctl --user is-active lock.target -q || playerctl play-pause' # KEY_PLAYPAUSE
  4:
    begin:
      command: 'systemctl --user is-active lock.target -q || swaync-client -t -sw'

threshold:
  swipe: 0.3
  pinch: 0.1

interval:
  swipe: 1
  pinch: 1
