# see /usr/include/linux/input-event-codes.h for key codes

swipe:
  3:
    left:
      command: 'systemctl --user is-active lock.target -q || ydotool key 56:1 106:1 106:0 56:0' # Alt + Right
    right:
      command: 'systemctl --user is-active lock.target -q || ydotool key 56:1 105:1 105:0 56:0' # Alt + Left
    up:
      begin:
        command: 'systemctl --user is-active lock.target -q || amixer -q sset Master unmute'
      update:
        command: 'systemctl --user is-active lock.target -q || ydotool key 115:1 115:0' # KEY_VOLUMEUP
        threshold: 0.05
    down:
      begin:
        command: 'systemctl --user is-active lock.target -q || amixer -q sset Master unmute'
      update:
        command: 'systemctl --user is-active lock.target -q || ydotool key 114:1 114:0' # KEY_VOLUMEDOWN
        threshold: 0.05
  4:
    left:
      update:
        command: 'ydotool key 224:1 224:0' # KEY_BRIGHTNESSDOWN
    right:
      update:
        command: 'ydotool key 225:1 225:0' # KEY_BRIGHTNESSUP

hold:
  3:
    command: 'systemctl --user is-active lock.target -q || ydotool key 164:1 164:0' # KEY_PLAYPAUSE
  4:
    command: 'systemctl --user is-active lock.target -q || swaync-client -t -sw'

threshold:
  swipe: 0.3
  pinch: 0.1

interval:
  swipe: 1
  pinch: 1
