# see /usr/include/linux/input-event-codes.h for key codes

swipe:
  3:
    left:
      command: 'ydotool key 56:1 106:1 106:0 56:0' # Alt + Right
    right:
      command: 'ydotool key 56:1 105:1 105:0 56:0' # Alt + Left
    up:
      begin:
        command: 'amixer -q sset Master unmute'
      update:
        #command: 'sh -c "amixer -q sset Master unmute && amixer -q sset Master 3%+"'
        command: 'ydotool key 115:1 115:0 115:1 115:0' # KEY_VOLUMEUP pressed two times
        threshold: 0.05
    down:
      begin:
        command: 'amixer -q sset Master unmute'
      update:
        #command: 'sh -c "amixer -q sset Master unmute && amixer -q sset Master 3%-"'
        command: 'ydotool key 114:1 114:0 114:1 114:0' # KEY_VOLUMEDOWN pressed two times
        threshold: 0.05
  4:
    left:
      update:
        command: 'ydotool key 224:1 224:0' # KEY_BRIGHTNESSDOWN
    right:
      update:
        command: 'ydotool key 225:1 225:0' # KEY_BRIGHTNESSUP

hold:
  3:
    command: 'ydotool key 164:1 164:0' # KEY_PLAYPAUSE

threshold:
  swipe: 0.3
  pinch: 0.1

interval:
  swipe: 1
  pinch: 1
