#!/usr/bin/env bash

(
  flock -n 9 || exit 0
  
  # Unmute the sink first
  wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
  
  # Decrease volume by parameter $1, or default to 5%
  wpctl set-volume @DEFAULT_AUDIO_SINK@ "${1:-1}"%-
  
  # Throttle the wheel scroll rate
  sleep 0.025
) 9>/tmp/$USER-volume-throttle.lock
