import = [
    "~/.config/alacritty/colors.toml",
    "~/.config/alacritty/fonts.toml"
]
live_config_reload = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/fish"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.95
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
